### ISSUE TITLE
Incorrect Courses in Default Degree Plan 

### ISSUE THREAD

**Issue by nealetham** [FA24-CSCE431-software-engineering/cleo-course-scheduler#121]
## Problem
According to this [sample catalog](https://engineering.tamu.edu/cse/_files/_documents/_content-documents/CSCE-Undergraduate-Degree-Plan-Computer-Science-Fall-2019.pdf), the default degree plan is wrong. Look at the last semester.

Because of this, there is a discrepancy with our actual degree builder.

## Solution
Do not hard code again. Pull from the database. Should be an easy fix.

**Comment by uzmahamid01** [comment]
Fixed
