### ISSUE TITLE
Non-uniform UI between Degree Builder and Default Degree

### ISSUE THREAD

**Issue by nealetham** [FA24-CSCE431-software-engineering/cleo-course-scheduler#122]
## Problem
As per the title.

![image](https://github.com/user-attachments/assets/1a13d0f9-83ef-497e-94eb-3c0d31c5088c)

![image](https://github.com/user-attachments/assets/937820e1-a493-43c6-bb52-ccbdf207e24c)

## Solution
Just reference the views in the Degree Builder. Join Course Code and Course Number. Display Course Name

**Comment by uzmahamid01** [comment]
Resolved
